version: '2.1'

services:
    database:
        image: "lozzikit-microservice-mail/database"
        environment:
            - MYSQL_DATABASE=lozzikit-mail
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3308:3306
        healthcheck:
            test: ["CMD", "mysql", "--user=root", "--password=root", "--execute=SHOW DATABASES;"]
            interval: 10s
            retries: 5

    smtp:
        image: "lozzikit-microservice-mail/smtp"
        environment:
            - MAILNAME=smtp.lozzikit.io
        healthcheck:
            test: ["CMD", "echo", "EHLO health@check.com", "|", "nc", "localhost", "25"]
            interval: 10s
            retries: 5

    server:
        image: lozzikit-microservice-mail/server
        ports:
            - 8080:8080
            - 5005:5005
        depends_on:
            database:
                condition: service_healthy
            smtp:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-sSfk", "http://localhost:8080/api/mail/v1/health"]
            interval: 10s
            timeout: 10s
            retries: 5
        links:
          - database:database.mail.microservice.lozzikit.io
          - smtp:smtp.lozzikit.io
