swagger: "2.0"
info:
    title: microservice-mail
    description: 'Mailing microservice for the AMT 2017 course @ HEIG-VD.'
    version: 0.1.0
paths:
    /mails:
        get:
            tags:
                - mail
            description: Get the mail history.
            responses:
                '200':
                    description: Returned the history successfuly.
        post:
            tags:
                - mail
            description: Send a mail (can use multiple payloads).
            responses:
                '200':
                    description: Mail sent successfuly.

    /mails/{id}:
        get:
            tags:
                - mail
            description: Get the status of a specified mail.
            responses:
                '200':
                    description: Returned the status successfuly.
        parameters:
            - in: path
              name: id
              description: The id of the mail we want to do something with.
              required: true
              type: integer

    /templates:
        get:
            tags:
                - template
            description: Get the list of available templates.
            responses:
                '200':
                    description: Returned the template list successfuly.
        post:
            tags:
                - template
            description: Create a new template.
            responses:
                '200':
                    description: Template has been created successfuly.

    /templates/{id}:
        get:
            tags:
                - template
            description: Get a specified template.
            responses:
                '200':
                    description: Returned the template successfuly.
        put:
            tags:
                - template
            description: Update a specified template.
            responses:
                '200':
                    description: Updated the template successfuly.
        delete:
            tags:
                - template
            description: Delete a specified template.
            responses:
                '200':
                    description: Deleted the template successfuly.
        parameters:
            - name: id
              in: path
              description: The id of the template we want to do something with.
              required: true
              type: integer

definitions:
    MailDto:
        type: object
        properties:
            id:
                type: integer

    TemplateDto:
        type: object
        properties:
            id:
                type: integer
            name:
                type: string
            description:
                type: string
            content:
                type: string
